AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  The Payment service is part of the ACME Serverless Shop. The goal of this specific service is to validate credit card payments.

Globals:
  Function:
    Timeout: 5

Parameters:
  Version:
    Type: String
  User:
    Type: String
  Team:
    Type: String
  Feature:
    Type: String
    Default: acmeserverless
  Stage:
    Type: String
    Default: dev
  WavefrontURL:
    Type: String
  WavefrontToken:
    Type: String

Resources:
  PaymentInboundQueue:
    Type: AWS::SQS::Queue
    Properties: 
      MessageRetentionPeriod: 120
      QueueName: !Sub '/${Stage}/${Feature}/payment/inbound'
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PDLQueue.Arn
        maxReceiveCount: 1
      Tags: 
        - Key: version
          Value: !Ref Version
        - Key: author
          Value: !Ref User
        - Key: team
          Value: !Ref Team
        - Key: feature
          Value: !Ref Feature
        - Key: region
          Value: !Ref AWS::Region
      VisibilityTimeout: 30
  PaymentOutboundQueue:
    Type: AWS::SQS::Queue
    Properties: 
      MessageRetentionPeriod: 120
      QueueName: !Sub '/${Stage}/${Feature}/payment/outbound'
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PDLQueue.Arn
        maxReceiveCount: 1
      Tags: 
        - Key: version
          Value: !Ref Version
        - Key: author
          Value: !Ref User
        - Key: team
          Value: !Ref Team
        - Key: feature
          Value: !Ref Feature
        - Key: region
          Value: !Ref AWS::Region
      VisibilityTimeout: 30
  PaymentInboundDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties: 
      MessageRetentionPeriod: 120
      QueueName: !Sub '/${Stage}/${Feature}/payment/inbound-dlq'
      Tags: 
        - Key: version
          Value: !Ref Version
        - Key: author
          Value: !Ref User
        - Key: team
          Value: !Ref Team
        - Key: feature
          Value: !Ref Feature
        - Key: region
          Value: !Ref AWS::Region
      VisibilityTimeout: 30
  PaymentOutboundDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties: 
      MessageRetentionPeriod: 120
      QueueName: !Sub '/${Stage}/${Feature}/payment/outbound-dlq'
      Tags: 
        - Key: version
          Value: !Ref Version
        - Key: author
          Value: !Ref User
        - Key: team
          Value: !Ref Team
        - Key: feature
          Value: !Ref Feature
        - Key: region
          Value: !Ref AWS::Region
      VisibilityTimeout: 30
  Payment:
    Type: AWS::Serverless::Function
    Properties:
      Handler: payment
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: Payment
      Description: A Lambda function to validate creditcard payments
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambdaRole
        - AWSLambdaSQSQueueExecutionRole
        - SQSSendMessagePolicy:
            QueueName: !Ref PaymentOutboundQueue
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          RESPONSE_QUEUE: !Ref PaymentOutboundQueue
          WAVEFRONT_ENABLED: true
          WAVEFRONT_URL: !Ref WavefrontURL
          WAVEFRONT_API_TOKEN: !Ref WavefrontToken
      Events:
        ValidateCreditcard:
          Type: SQS
          Properties:
            Queue: !GetAtt PaymentInboundQueue.Arn
            BatchSize: 1
            Enabled: true
      Tags:
        version: !Ref Version
        author: !Ref User
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version

Outputs:
  PaymentsARN:
    Description: ARN for the Payment function
    Value: !GetAtt Payment.Arn
  PaymentInboundQueueARN:
    Description: ARN for the Payment Inbound Queue
    Value: !GetAtt PaymentInboundQueue.Arn
  PaymentOutboundQueueARN:
    Description: ARN for the Payment Outbound Queue
    Value: !GetAtt PaymentOutboundQueue.Arn
  PaymentInboundDeadLetterQueueARN:
    Description: ARN for the Payment Inbound DeadLetter Queue
    Value: !GetAtt PaymentInboundDeadLetterQueue.Arn
  PaymentOutboundDeadLetterQueueARN:
    Description: ARN for the Payment Outbound DeadLetter Queue
    Value: !GetAtt PaymentOutboundDeadLetterQueue.Arn